### ISSUE TITLE
Collecting of coverage value using plugin

### ISSUE THREAD

**Issue by roomanidzee** [kotest/kotest-gradle-plugin#15]
How to preferrable collect the coverage from tests, using the kotest-gradle-plugin?

I tried to use jacoco, but after calling ```gradle kotest jacocoTestReport``` there will be an empty folder with jacoco reports.

can't send settings for reproduce , sorry.

can you help, please, with such feature?

**Comment by sksamuel** [comment]
jacoco is probably invoking test, I doubt it's gonna work with the gradle
plugin without some custom work.

**Comment by rezammalik** [comment]
What i've done is a workaround where unit tests with coverage run via the test command and for integrations I am using kotest. This works for now for me.

**Comment by sksamuel** [comment]
Reading the jacoco docs, it seems like it should be relatively easy to do:

_all tasks of type Test are aautomatically enhanced to provide coverage information when the java plugin has been applied_

The kotest plugin uses a task of type test.

**Comment by sksamuel** [comment]
tasks.create("testtypes") {
   tasks.withType<Test> {
      println("hello $this")
   }
}

> Configure project :
hello task ':kotest'
hello task ':test'


So Kotest is being picked up properly as a "Test" type.

From jacoco:


https://github.com/gradle/gradle/blob/master/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPlugin.java#L134-L136


So.... it might be as simple as making sure the jacoco plugin runs
AFTER kotest. My guess is they run in alphabetical order?

**Comment by roomanidzee** [comment]
probably yes, in alphabetical order

there should be some additional config in build.gradle.kts, or it should just work like this: ```gradle kotest jacocoTestReport``` ?

**Comment by sksamuel** [comment]
I don't use jacoco myself, but we could create a sample project I suppose.

I think you might have to declare them in alphabetical order in your build
(not the order you run them at the CLI).

**Comment by roomanidzee** [comment]
@sksamuel will be very great, thank you!

**Comment by rezammalik** [comment]
This would be a nice feature for me too where I can run everything via `kotest` instead of `test` and then filter the unit tests using our other `tag` feature.
