### ISSUE TITLE
Remove deprecated JavaSourceConvention

### ISSUE THREAD

**Issue by donat** [kotest/kotest-gradle-plugin#42]
JavaSourceConvention is deprecated and scheduled for removal in Gradle 9. In Gradle 8 we plan to add a deprecation message.
Also, DefaultJavaSourceConvention is an internal API and is subject to change (and will change if https://github.com/gradle/gradle/pull/22086 gets merged). The source sets can already be accessed by using `JavaSourceConvention`.

https://github.com/kotest/kotest-gradle-plugin/blob/2797165ca8285e0d6dc6065baf463e2dcc525a46/src/main/kotlin/io/kotest/gradle/sourcesets.kt#L54

**Comment by Kantis** [comment]
Still actual
